"""empty message

Revision ID: 5594d76e88a9
Revises: 678cbb80def1
Create Date: 2023-03-02 21:10:17.724033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5594d76e88a9'
down_revision = '678cbb80def1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sale_oportunity', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('is_sale_oportunity')

    # ### end Alembic commands ###
