"""empty message

Revision ID: 678cbb80def1
Revises: 17ba4133c15f
Create Date: 2023-03-02 20:46:12.716039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678cbb80def1'
down_revision = '17ba4133c15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commercial_name', sa.String(length=70), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.Enum('YELLOW', 'BLUE', 'GRAY', name='carcolors'), nullable=False),
    sa.Column('model', sa.Enum('HATCH', 'SEDAN', 'CONVERTIBLE', name='carmodels'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
