"""empty message

Revision ID: da769b56060f
Revises: 5594d76e88a9
Create Date: 2023-03-02 21:16:15.195993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da769b56060f'
down_revision = '5594d76e88a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_number', sa.String(length=30), nullable=False))
        batch_op.create_unique_constraint(None, ['document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('document_number')

    # ### end Alembic commands ###
